var searchData=
[
  ['collections',['Collections',['../namespace_system_1_1_collections.html',1,'System']]],
  ['compilerservices',['CompilerServices',['../namespace_system_1_1_runtime_1_1_compiler_services.html',1,'System::Runtime']]],
  ['comtypes',['ComTypes',['../namespace_system_1_1_runtime_1_1_interop_services_1_1_com_types.html',1,'System::Runtime::InteropServices']]],
  ['generated',['Generated',['../namespace_system_1_1_runtime_1_1_serialization_1_1_generated.html',1,'System::Runtime::Serialization']]],
  ['generic',['Generic',['../namespace_system_1_1_collections_1_1_generic.html',1,'System::Collections']]],
  ['interopservices',['InteropServices',['../namespace_system_1_1_runtime_1_1_interop_services.html',1,'System::Runtime']]],
  ['io',['IO',['../namespace_system_1_1_i_o.html',1,'System']]],
  ['properties',['Properties',['../namespace_sample_wdp_client_1_1_properties.html',1,'SampleWdpClient']]],
  ['runtime',['Runtime',['../namespace_system_1_1_runtime.html',1,'System']]],
  ['samplewdpclient',['SampleWdpClient',['../namespace_sample_wdp_client.html',1,'']]],
  ['samplewdpclient_5funiversalwindows_5fxamltypeinfo',['SampleWdpClient_UniversalWindows_XamlTypeInfo',['../namespace_sample_wdp_client_1_1_universal_windows_1_1_sample_wdp_client___universal_windows___xaml_type_info.html',1,'SampleWdpClient::UniversalWindows']]],
  ['serialization',['Serialization',['../namespace_system_1_1_runtime_1_1_serialization.html',1,'System::Runtime']]],
  ['system',['System',['../namespace_system.html',1,'']]],
  ['threading',['Threading',['../namespace_system_1_1_threading.html',1,'System']]],
  ['universalwindows',['UniversalWindows',['../namespace_sample_wdp_client_1_1_universal_windows.html',1,'SampleWdpClient']]],
  ['windowsruntime',['WindowsRuntime',['../namespace_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime.html',1,'System::Runtime::InteropServices']]]
];
